title: GIA-UH

description: >
  Grupo de investigación GIA (Grupo de Inteligencia Artificial) de la Universidad de La Habana.

# show_downloads: true

google_analytics:
remote_theme: mmistakes/minimal-mistakes
plugins: jekyll-include-cache
