title: GIA-UH

description: >
  El grupo de investigaci칩n GIA (Grupo de Inteligencia Artificial) de la Universidad de La Habana, dirigido
  actualmente por el Dr. Yudivi치n Almeida, pertenece al departamento de Inteligencia Artificial y Sistemas
  Computacionales, de la Facultad de Matem치tica y Computaci칩n de la Universidad de La Habana.

google_analytics:
theme: jekyll-theme-slate

links:
  - name: Post
    url: /
    external: false
  - name: SobreMi
    url: /about
    external: false