title: GIA-UH

description: >
  Grupo de investigación GIA (Grupo de Inteligencia Artificial) de la Universidad de La Habana.

google_analytics:
theme: jekyll-theme-leap-day

links:
  - name: Post
    url: /
    external: false
  - name: SobreMi
    url: /about
    external: false